### ISSUE TITLE
How often do you refresh github data?

### ISSUE THREAD

**Issue by styfle** [cheeaun/repokemon#13]
How often do you refresh github data?

I have a new repo called [exeggcute](https://github.com/styfle/exeggcute) that is just dying to get in there. :egg: :smile:

**Comment by cheeaun** [comment]
I'm not sure how often I would refresh the data yet. Perhaps every two weeks or every month 😄

And also, nice repo 😃

**Comment by cheeaun** [comment]
Closing this. I've also added a [Criteria](https://github.com/cheeaun/repokemon#criteria) section which makes it much harder to be part of this list. Fortunately your repo qualifies to be in the list 😄  Cheers!

**Comment by styfle** [comment]
Good deal, thanks!
