### ISSUE TITLE
Voltorb image is wrong

### ISSUE THREAD

**Issue by gnclmorais** [cheeaun/repokemon#14]
[Misdreavus](http://bulbapedia.bulbagarden.net/wiki/Misdreavus_(Pok%C3%A9mon)) is being shown instead (centre of the picture):
![image](https://cloud.githubusercontent.com/assets/385232/17117477/102a4280-52b4-11e6-8f0a-8899eac3c425.png)

**Comment by cheeaun** [comment]
Hey thanks a lot!! Fixed in 96fcff93c48dfd4f2754d1bb6aa3dd7ad8b4ac06 😄

**Comment by gnclmorais** [comment]
Great project, btw! All things Pokémon 💟
