### ISSUE TITLE
Add Meltan and Melmetal?

### ISSUE THREAD

**Issue by shadowrylander** [cheeaun/repokemon#18]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; Sorry if you're already doing this, but I was wondering whether it would be possible to add [Meltan](https://bulbapedia.bulbagarden.net/wiki/Meltan_(Pok%C3%A9mon)) and [Melmetal](https://bulbapedia.bulbagarden.net/wiki/Melmetal_(Pok%C3%A9mon)) to the database, if new Pokemon are not automatically added? <br>
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for your consideration, and apologies if this already happens!

**Comment by cheeaun** [comment]
Now added in f86a1ce246dcb932979155dd430a8640b14d4f04

<img width="322" alt="screenshot 2019-02-23 at 4 48 45 pm" src="https://user-images.githubusercontent.com/2296/53284144-e9db7900-378a-11e9-9fca-313c5713803c.png">

**Comment by shadowrylander** [comment]
Er, quick note: incorrect art using [Magearna](https://bulbapedia.bulbagarden.net/wiki/Magearna_(Pok%C3%A9mon)) ...?

**Comment by cheeaun** [comment]
@shadowrylander lol! totally missed that 😅Fixed in ced776b25fcc974c10e2f653af751d7325a4154a

<img width="312" alt="screenshot 2019-02-24 at 11 47 24 am" src="https://user-images.githubusercontent.com/2296/53294852-04186400-382a-11e9-9064-534e04e5d6d0.png">

**Comment by shadowrylander** [comment]
Thanks! 😸
