### ISSUE TITLE
The mid-January Action failed

### ISSUE THREAD

**Issue by matt-dray** [cheeaun/repokemon#26]
Thank you for this project, @cheeaun. In case you hadn't spotted it yet, the last execution of the GitHub Action [failed](https://github.com/cheeaun/repokemon/actions/runs/3920882163/jobs/6702765872), so the latest data is from 1 Jan 2023 rather than from two weeks ago. I assume this may impact the scheduled Action for 1 Feb in a couple of days as well. 👀

**Comment by cheeaun** [comment]
Thanks! Seems like it finally reach 1K pokemons, so the numbers/IDs/image-paths are no longer 3 digits (on their side - pokemon's site).

Fixed now.
