### ISSUE TITLE
Wrong images

### ISSUE THREAD

**Issue by wahlp** [cheeaun/repokemon#33]
Pokemon number 1001 to 1009 is showing 101 to 109, and number 100 doesn't appear. See middle row of screenshot
![image](https://github.com/user-attachments/assets/0b6be8ad-ac8a-430b-a649-fd31b55b2381)

Pokemon number 1000 is showing number 200. See middle of screenshot
![image](https://github.com/user-attachments/assets/7d0ffe59-60e8-49b7-b4aa-ee4f39d6cea6)

**Comment by cheeaun** [comment]
Should be fixed now.

**Comment by wahlp** [comment]
The fixes for the above bugs seem to have messed up the "most stars" view

![image](https://github.com/user-attachments/assets/97bcf780-9399-4629-9d60-0ef284d3a37c)

**Comment by cheeaun** [comment]
Thanks! Should be fixed now (again) 🙏

**Comment by wahlp** [comment]
Seems like everything is fixed, thanks for maintaining this project!
