### ISSUE TITLE
My Little Pony equivalent

### ISSUE THREAD

**Issue by drom** [cheeaun/repokemon#5]
Any idea where to scrape the database?

**Comment by cheeaun** [comment]
Hmm I don't watch My Little Pony, but I guess a little googling shows this? http://mlp.wikia.com/wiki/Characters

**Comment by drom** [comment]
@cheeaun it is HTML page. How would you get JSON of this?

**Comment by cheeaun** [comment]
@drom you probably need to scrape the HTML page 😅

**Comment by cheeaun** [comment]
Closing this, because kinda irrelevant for this repo 😅 

Hope I helped answering your question! 😄
